# Where should we write the GIF?
Output assets/demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 18
Set Width 1200
Set Height 800

# Welcome!
Type "echo 'Welcome to llm repl command!'"
Sleep 2s
Enter

# Run the command by pressing enter.
Type "llm repl"
Sleep 500ms
Enter

Type "Count from 1 to 10 in words!"
Enter
Sleep 5s

Type "Now let's switch to multi-line mode by pressing Ctrl+Space!"
Sleep 5s
Ctrl+R # vhs don't support Ctrl+Space :'(
Enter
Type "As you can see I can add extra"
Enter
Type "new lines quite easily!"
Alt+Enter
Sleep 5s

Ctrl+R
Type "Write a Python class"
Enter
Sleep 10s
